language: cpp
dist: bionic
compiler: gcc

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default
  - sudo apt-get install -qq libqt5svg5-dev
  # Qwt
  - sudo apt-get install -qq libqwt-qt5-dev
  # cppcheck
  - sudo apt-get install -qq cppcheck
  # Codecov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint.sh
  # valgrind, for helgrind and memcheck
  - sudo apt-get install -qq valgrind
  # SLOCcount
  - sudo apt-get install sloccount
  # Get my folder
  - my_github=${PWD##*/}  
  # shunit2
  - cd ..; git clone https://github.com/kward/shunit2.git; cd $my_github
  # GSL and other GitHubs
  - my_github=${PWD##*/}  
  - cd ..
  - git clone https://github.com/Microsoft/GSL
  - git clone -b develop https://github.com/richelbilderbeek/boost_graph_cookbook_1
  - git clone -b develop https://github.com/richelbilderbeek/ConceptMap
  - git clone -b develop https://github.com/richelbilderbeek/plane
  - git clone -b develop https://github.com/richelbilderbeek/QtConceptMap
  - git clone -b develop https://github.com/richelbilderbeek/QtKeyboardFriendlyGraphicsView
  - git clone -b develop https://github.com/richelbilderbeek/RibiClasses
  - git clone -b develop https://github.com/richelbilderbeek/RibiLibraries
  - git clone -b develop https://github.com/richelbilderbeek/StyleSheetSetter
  - cd $my_github
  - ./download_other_githubs.sh
  - ./build_other_githubs.sh

# Xenial
services:
 - xvfb

script: 
  # Build console tests
  - qmake -qt=qt5 KalmanFilterTestConsole.pro
  - make --silent
  # Build desktop tests
  - qmake -qt=qt5 KalmanFilterTestDesktop.pro
  - make --silent debug
  # Build console
  - qmake -qt=qt5 KalmanFiltererConsole.pro
  - make --silent
  # Build desktop
  - qmake -qt=qt5 KalmanFiltererDesktop.pro
  - make --silent
  # Run tests
  - ./KalmanFilterTestConsole
  - ./KalmanFilterTestDesktop
  # Run normal programs
  - ./KalmanFiltererDesktop &
  - sleep 10
  - sudo killall -9 KalmanFiltererDesktop
  # Code coverage
  - ./get_code_cov.sh >/dev/null
  - codecov >/dev/null
  # OCLint
  - ./do_oclint.sh

after_success: 
  - bash <(curl -s https://codecov.io/bash)
